/** Kinetic Enterprise 팔레트 — architecture/design/stitch/DESIGN.md (source of truth).
 *  새 색/폰트를 생성하지 않는다. mockup(PR2.html 등)과 동일 토큰. */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f9',
        'surface-dim': '#dbdad9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e3e2e2',
        'surface-light': '#F8F9FA',
        'surface-border': '#DCDCDC',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#434751',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        outline: '#747782',
        'outline-variant': '#c4c6d2',
        'surface-tint': '#395da2',
        primary: '#00204e',
        'on-primary': '#ffffff',
        'primary-container': '#003478',
        'on-primary-container': '#7d9fe9',
        'inverse-primary': '#aec6ff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#aec6ff',
        secondary: '#005db7',
        'on-secondary': '#ffffff',
        'secondary-container': '#599bfe',
        tertiary: '#4d000a',
        'tertiary-container': '#750015',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbf9f9',
        'on-background': '#1b1c1c',
        'text-primary': '#000000',
        'text-secondary': '#555555',
        'text-disabled': '#BEBEBE',
        'accent-red': '#E63946',
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      spacing: {
        xs: '4px', sm: '8px', md: '16px', lg: '24px', xl: '32px',
        gutter: '24px', 'margin-mobile': '16px', 'margin-desktop': '48px',
      },
      borderRadius: { DEFAULT: '0.5rem', md: '0.75rem', lg: '1rem', xl: '1.5rem' },
    },
  },
  plugins: [],
}
